//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public int FeedId { get; set; }
        public string FeedUrl { get; set; }
        public string FeedImg { get; set; }
    }
}
