//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkComment
    {
        public int LinkCommentId { get; set; }
        public Nullable<int> LinkId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string CommentText { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Link Link { get; set; }
    }
}
