//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteId { get; set; }
        public Nullable<int> LinkId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Link Link { get; set; }
    }
}
